"use client";

//import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import { WagmiProvider } from 'wagmi';
import { config } from "../lib/wagmi";

import {
  DynamicContextProvider,
  EthereumWalletConnectors,
  DynamicWagmiConnector
} from "@/lib/dynamic";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

const dynamicEnvId = process.env.NEXT_PUBLIC_DYNAMIC_ENV_ID;

const evmNetworks = [
  {
    blockExplorerUrls: ['https://sepolia.etherscan.io/'],
    chainId: 11155111,
    chainName: 'Sepolia',
    iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
    name: 'Sepolia',
    nativeCurrency: {
      decimals: 18,
      name: 'Sepolia Ether',
      symbol: 'ETH',
    },
    networkId: 11155111,
    rpcUrls: ['https://sepolia.infura.io/v3/'],
    vanityName: 'Sepolia',
  },
  {
    blockExplorerUrls: ['https://cardona-zkevm.polygonscan.com'],
    chainId: 2442,
    chainName: 'Polygon zkEVM Cardona Testnet',
    iconUrls: ['https://logowik.com/content/uploads/images/polygon-matic-icon3725.logowik.com.webp'],
    name: 'Polygon zkEVM Cardona Testnet',
    nativeCurrency: {
      decimals: 18,
      name: 'ETH',
      symbol: 'ETH',
    },
    networkId: 2442,
    rpcUrls: ['https://polygon-zkevm-cardona.blockpi.network/v1/rpc/public'],
    vanityName: 'Polygon zkEVM Cardona Testnet',
  },
 {
    blockExplorerUrls: ['https://explorer.testnet.rsk.co/'],
    chainId: 31,
    chainName: 'Rootstock Testnet',
    iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
    name: 'Rootstock Testnet',
    nativeCurrency: {
      decimals: 18,
      name: 'Rootstock Testnet BTC',
      symbol: 'rBTC',
    },
    networkId: 31,
    rpcUrls: ['https://public-01.testnet.rsk.co/rpc'],
    vanityName: 'Rootstock Testnet',
  },
  {
    blockExplorerUrls: ['https://sepolia-explorer.base.org/'],
    chainId: 84532,
    chainName: 'Base Sepolia',
    iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
    name: 'Base Sepolia',
    nativeCurrency: {
      decimals: 18,
      name: 'Base ETH',
      symbol: 'ETH',
    },
    networkId: 84532,
    rpcUrls: ['https://sepolia.base.org'],
    vanityName: 'Base Sepolia',
  },
  {
    blockExplorerUrls: ['https://evm-testnet.flowscan.io'],
    chainId: 545,
    chainName: 'Flow',
    iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
    name: 'EVM on Flow Testnet',
    nativeCurrency: {
      decimals: 18,
      name: 'Flow',
      symbol: 'FLOW',
    },
    networkId: 545,
    rpcUrls: ['https://testnet.evm.nodes.onflow.org'],
    vanityName: 'EVM on Flow Testnet',
  },
];

const cssOverrides = `
@media (max-width: 767px) {
  .network-picker-network-control {
    display: none;
  }
}
`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DynamicContextProvider
          settings={{
            environmentId: dynamicEnvId || "",
            walletConnectors: [EthereumWalletConnectors],
            overrides: { evmNetworks },
            cssOverrides: cssOverrides,
          }}>
          <WagmiProvider config={config}>
            <QueryClientProvider client={queryClient}>
              <DynamicWagmiConnector>

                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem
                  disableTransitionOnChange
                >
                  {children}
                </ThemeProvider>
              </DynamicWagmiConnector>
            </QueryClientProvider>
          </WagmiProvider>
        </DynamicContextProvider>
      </body>
    </html>
  );
}
